# Generated by Django 4.0.4 on 2022-09-22 15:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=60)),
                ('priority', models.CharField(choices=[('Urgent', 'Urgent'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=6)),
                ('state', models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Awaiting Feedback', 'Awaiting Feedback'), ('Done', 'Done')], default='To Do', max_length=17)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
